# Generated by Django 2.0.5 on 2020-01-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(blank=True, max_length=100, verbose_name='四级部门')),
                ('project', models.CharField(blank=True, max_length=100, verbose_name='项目')),
                ('troubletype', models.CharField(blank=True, max_length=100, verbose_name='事故定级')),
                ('troubledesc', models.CharField(blank=True, max_length=1000, verbose_name='问题描述')),
                ('mainside', models.CharField(blank=True, max_length=100, verbose_name='主责方')),
                ('otherside', models.CharField(blank=True, max_length=100, verbose_name='次责方')),
                ('troubletime', models.CharField(blank=True, max_length=100, verbose_name='事故时间')),
                ('effacttime', models.CharField(blank=True, max_length=100, verbose_name='线上影响时间')),
                ('effactusercnt', models.CharField(blank=True, max_length=100, verbose_name='影响用户量')),
                ('effactmoney', models.CharField(blank=True, max_length=100, verbose_name='影响金额')),
                ('delete_flag', models.CharField(default='0', max_length=1, verbose_name='是否删除，0是非删除，1是删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(blank=True, max_length=100, verbose_name='四级部门')),
                ('project', models.CharField(blank=True, max_length=100, verbose_name='项目名称-大类')),
                ('taskName', models.CharField(blank=True, max_length=100, verbose_name='任务名称')),
                ('taskLink', models.CharField(blank=True, max_length=100, verbose_name='任务链接')),
                ('subTest', models.CharField(blank=True, max_length=100, verbose_name='提测时间')),
                ('oldTestTime', models.CharField(blank=True, max_length=100, verbose_name='原测试时间')),
                ('newTestTime', models.CharField(blank=True, max_length=100, verbose_name='调整后测试时间')),
                ('onlineTime', models.CharField(blank=True, max_length=100, verbose_name='上线时间')),
                ('testPerson', models.CharField(blank=True, max_length=100, verbose_name='测试人员')),
                ('taskStatus', models.CharField(blank=True, max_length=100, verbose_name='任务状态')),
                ('tag', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('importance', models.CharField(default='0', max_length=1, verbose_name='是否重点任务，0是非重点，1是重点')),
                ('delete_flag', models.CharField(default='0', max_length=1, verbose_name='是否删除，0是非删除，1是删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
