# Generated by Django 2.0.5 on 2020-01-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(blank=True, max_length=100, verbose_name='四级部门名')),
                ('shareperson', models.CharField(blank=True, max_length=100, verbose_name='分享人')),
                ('sharetime', models.CharField(blank=True, max_length=100, verbose_name='分享时间')),
                ('sharetitle', models.CharField(blank=True, max_length=100, verbose_name='分享主题')),
                ('shareaddress', models.CharField(blank=True, max_length=100, verbose_name='分享地址')),
                ('delete_flag', models.CharField(default='0', max_length=1, verbose_name='是否删除，0是非删除，1是删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
