# Generated by Django 2.0.5 on 2020-01-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastDepartment', models.CharField(blank=True, max_length=100, verbose_name='三级部门')),
                ('team', models.CharField(blank=True, max_length=100, verbose_name='四级部门')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='用户登录名')),
                ('realname', models.CharField(blank=True, max_length=100, verbose_name='真实姓名')),
                ('email', models.TextField(blank=True, default='', verbose_name='邮箱')),
                ('business_group', models.CharField(blank=True, max_length=100, verbose_name='事业群')),
                ('lastDepartment', models.CharField(blank=True, max_length=100, verbose_name='上级部门')),
                ('team', models.CharField(blank=True, max_length=100, verbose_name='团队')),
                ('group_data', models.CharField(blank=True, max_length=500, verbose_name='部门具体信息原始数据')),
                ('department_list', models.CharField(blank=True, max_length=500, verbose_name='部门层级列表')),
                ('status', models.CharField(blank=True, default='1', max_length=100, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='UsersColor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='颜色')),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.Users')),
            ],
        ),
    ]
